batik-ext deps needed to workaround BATIK-1229
java.lang.NoClassDefFoundError: org/apache/batik/w3c/dom/ElementTraversal
see https://jira.apache.org/jira/browse/BATIK-1229 for details